name: CI & Deploy to Fly

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install & Build with Vite
        run: |
          npm ci
          npm run build
          npm run build:server

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly Deploy
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}